[package]
name = "app"
version = "0.1.0"
authors = ["Daniel Wilkins <danielwilkins8@gmail.com>"]

[dependencies]
webplatform = "*"
maud = { version = "*" }
maud_macros = "*"
libc = "0.2.16"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"